/** @type {import('tailwindcss').Config} */
// Design tokens copied from the Stitch export (Tailwind v3 syntax).
// Merge the `extend` block into your existing config if you already have one.
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bfc9c3",
        secondary: "#006c4e",
        "on-surface": "#131b2e",
        "primary-fixed": "#b0f0d6",
        "secondary-fixed-dim": "#7bd8b1",
        outline: "#707974",
        "on-secondary": "#ffffff",
        "inverse-primary": "#95d3ba",
        primary: "#003527",
        "on-error": "#ffffff",
        "surface-container": "#eaedff",
        error: "#ba1a1a",
        "on-surface-variant": "#404944",
        surface: "#faf8ff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#0b513d",
        "surface-container-highest": "#dae2fd",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#97f5cc",
        "surface-container-high": "#e2e7ff",
        "surface-container-low": "#f2f3ff",
        "inverse-surface": "#283044",
        "error-container": "#ffdad6",
        "on-secondary-container": "#007353",
        "on-primary-container": "#80bea6",
        "primary-fixed-dim": "#95d3ba",
        "primary-container": "#064e3b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        gutter: "0.75rem",
        margin: "1rem",
      },
      fontFamily: {
        "label-ui": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "numeric-metric-lg": ["JetBrains Mono", "monospace"],
        "numeric-metric-md": ["JetBrains Mono", "monospace"],
        "numeric-metric-sm": ["JetBrains Mono", "monospace"],
        "label-mono-micro": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-ui": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "numeric-metric-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "numeric-metric-md": ["14px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "numeric-metric-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-mono-micro": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};